#! /usr/bin/python
# -*- coding: utf-8 -*-

from lxml import html
import requests
import argparse
import re

GR = '\033[0;30m' # gray
RR = '\033[1;31m' # red bold
R = '\033[0;31m' # red
GG = '\033[1;32m' # green bold
G = '\033[0;32m' # green
YY = '\033[1;33m' # yellow bold
Y = '\033[0;33m' # yellow
BB = '\033[1;34m' # blue bold
B = '\033[0;34m' # blue
P = '\033[1;35m' # purple
C = '\033[0;36m' # cyan
D = '\033[0;0m'  # default

def escape(strarr):
    text = ' '.join(strarr).encode('latin1')
    text = text.replace('\r', ' ').replace('\t', ' ').replace('\xa0', ' ').strip()
    return re.sub(' +', ' ', text)

def header(cod):
    print G+'''
        ###################
        #  %s%s%s  #
        ###################
    ''' % (D,cod,G)

def check(status):
    if 'postado' in status:
        color = RR
    elif 'entregue' in status:
        color = GG
    elif 'entrega' in status:
        color = YY
    else:
        color = BB

    return color + '=> '

def rastreio(obj):
    s = requests.Session()

    obj_post = {
        'objetos': obj,
        'btnPesq': '+Buscar'
    }

    s.headers.update({
        'Host': 'www2.correios.com.br',
        'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3',
        'Accept-Encoding': 'gzip, deflate',
        'Referer': 'http://www2.correios.com.br/sistemas/rastreamento/default.cfm',
        'Content-Type': 'application/x-www-form-urlencoded',
        'Content-Length': '37',
        'Connection': 'keep-alive',
        'Upgrade-Insecure-Requests': '1'
    })

    r = s.post('http://www2.correios.com.br/sistemas/rastreamento/resultado.cfm?', data=obj_post, allow_redirects=True)
    r.encoding = 'ISO-8859-1'

    if r.status_code == 200:
        if r.text.find('listEvent') == -1:
            print YY+'['+R+'#'+YY+'] Erro na requisição'
            return None

        tree = html.fromstring(r.text.encode('latin1'))
        trs = tree.xpath('//table[contains(@class,"listEvent")]/tr')

        for tr in trs:
            tds = tr.xpath('./td')

            data = escape(tds[0].xpath('./text() | ./label/text()'))
            text = escape(tds[1].xpath('./text()'))
            status = tds[1].xpath('./strong/text()')[0]

            print YY + data
            print check(status) + C + status
            print D + text
            print P + '--------------------------------------------------' + D

if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        prog='rastreio',
        usage='%(prog)s <codigo[,codigo2,codigo3]>',
        description='Script para rastrear pacotes dos correios'
    )

    parser.add_argument("c", metavar="codigo", type=str, help="codigo do rastreio")
    args = parser.parse_args()
    codigos = [cod for cod in args.c.split(',') if len(cod) == 13]

    if len(codigos) >= 1:
        for cod in codigos:
            header(cod)
            rastreio(cod)
    else:
        parser.print_help()
